spring:
  h2:
    console:
      path: /h2-consle
      enabled: true
  datasource:
    generate-unique-name: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
